version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./src/mysql_data:/var/lib/mysql
    expose:
      - "3306"

  web1:
    build: ./src
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:setup && rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    tmpfs:
      - /tmp/pids
    
    expose:
      - "8080"
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: src_development
      PIDFILE: /tmp/pids/server.pid
    image: shubhamrasal007/iris:latest
    
  web2:
    build: ./src
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8081 -b '0.0.0.0'"

    volumes:
      - ./src:/myapp
    tmpfs:
      - /tmp/pids
    expose:
      - "8081"
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: src_development
      PIDFILE: /tmp/pids/server.pid
    image: shubhamrasal007/iris:latest
    
  web3:
    build: ./src
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8082 -b '0.0.0.0'"
    volumes:
      - ./src:/myapp
    tmpfs:
      - /tmp/pids
    expose:
      - "8082"
    depends_on:
      - db
    links:
      - db
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: src_development
      PIDFILE: /tmp/pids/server.pid
    image: shubhamrasal007/iris:latest
    

  nginx:
      build: ./src/nginx
      ports:
        - "8090:8090"
      depends_on:
        - web1
        - web2
        - web3
        - db
      volumes:
        - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./src/nginx/log:/var/log/nginx     
     
      restart: always
      image: shubhamrasal007/nginx:latest
  

volumes:
  mysql_data:


      
      


      
      
      