name: Docker Compose Actions Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose build    
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push to Docker Hub
        run: docker-compose push

      - 
        name: Health Check
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install requests
      - run: python .github/workflows/health_check.py
      
        

      

  

  
     