steps:
  # need checkout before using compose-action
  - uses: actions/checkout@v3
  - uses: isbang/compose-action@v1.4.1
    with:
      compose-file: "docker-compose.yml"
      down-flags: "--volumes"
      services: |
        web1
        web2
        web3
        db
        nginx
      up-flags: "--build --force-recreate"